// Dados do Party Infernum — personagens e times da guild.
// Estrutura simples em arrays de objetos.

const CHARACTERS = [
  {vendido:false, nome:"Necroyster", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"Arthur#1", voc:"🧝🏼 ED [Elder Druid]", level:1130, primal:"12/12", soulwar:true, sanguine:true, graveborn:false},
  {vendido:false, nome:"Voyeur Hot Yoga", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:845, primal:"12/12", soulwar:true, sanguine:true, graveborn:true},
  {vendido:false, nome:"Andicecream", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"Arthur#1", voc:"🧕🏼 EM [Exalted Monk]", level:830, primal:"12/12", soulwar:true, sanguine:true, graveborn:false},
  {vendido:false, nome:"Bvlgary", servidor:"Belaria 🟢", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:810, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Redhaired Shanks", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"", voc:"👷RP [Royal Paladin]", level:720, primal:"12/12", soulwar:true, sanguine:true, graveborn:false},
  {vendido:false, nome:"Creatina Frescca", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:690, primal:"12/12", soulwar:true, sanguine:true, graveborn:false},
  {vendido:false, nome:"Fupp", servidor:"Solarian 🟢 🛡", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:650, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Mambalexq", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"", voc:"👷RP [Royal Paladin]", level:560, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Best", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"", voc:"🧑‍🚒 EK [Elite Knight]", level:550, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Reqviem", servidor:"Serenian [Eldrian] 🟢 🛡🚫", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:540, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Gabi Trans Nao Operada", servidor:"Auroria 🟠", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:406, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Sir Peace", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"", voc:"🧙‍♂️ MS [Master Sorcerer]", level:400, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Dra Marcia", servidor:"Grimoria III [Drakaria] 🟢 🚫", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:240, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Holiex On Grimoria", servidor:"Grimoria II [Malveria] 🟢 🚫", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:374, primal:"4/12", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Mango Jvicy", servidor:"Belaria 🟢", conta:"", voc:"🧙‍♂️ MS [Master Sorcerer]", level:350, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Dono da Sauna", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"Gmail", voc:"🧝🏼 ED [Elder Druid]", level:298, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Dolly Citros", servidor:"Infernum 🟢 ⚔🚫", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:0, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Dieguito Maradona", servidor:"Grimoria II [Malveria] 🟢 🚫", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:650, primal:"2/12", soulwar:null, sanguine:null, graveborn:null},
  {vendido:false, nome:"Primo do Luis", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"ThiagoG#1", voc:"👷RP [Royal Paladin]", level:758, primal:"12/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Maricas", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"ThiagoG#1", voc:"🧑‍🚒 EK [Elite Knight]", level:607, primal:"5/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Sabor Ice", servidor:"", conta:"", voc:"", level:null, primal:"", soulwar:null, sanguine:null, graveborn:null},
  {vendido:false, nome:"Leao cabecinha", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"Marcelo#1", voc:"🧑‍🚒 EK [Elite Knight]", level:730, primal:"", soulwar:true, sanguine:true, graveborn:false},
  {vendido:false, nome:"Ek Escolta", servidor:"Grimoria II [Malveria] 🟢 🚫", conta:"Marcelo#1", voc:"🧑‍🚒 EK [Elite Knight]", level:915, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Bloody Mind", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"Marcelo#1", voc:"🧑‍🚒 EK [Elite Knight]", level:870, primal:"7/12", soulwar:true, sanguine:true, graveborn:false},
  {vendido:false, nome:"Two Handed Sword", servidor:"Serenian [Eldrian] 🟢 🛡🚫", conta:"Marcelo#1", voc:"🧑‍🚒 EK [Elite Knight]", level:1000, primal:"", soulwar:true, sanguine:true, graveborn:false},
  {vendido:false, nome:"Ekdofin", servidor:"Serenian [Eldrian] 🟢 🛡🚫", conta:"Marcelo#1", voc:"🧑‍🚒 EK [Elite Knight]", level:1000, primal:"", soulwar:true, sanguine:true, graveborn:true},
  {vendido:false, nome:"Mago Win", servidor:"Tenebrium 🟢 ⚔🚫", conta:"Marcelo#1", voc:"🧙‍♂️ MS [Master Sorcerer]", level:1000, primal:"", soulwar:true, sanguine:true, graveborn:false},
  {vendido:false, nome:"Knight Hot Yoga", servidor:"Grimoria II [Malveria] 🟢 🚫", conta:"Marcelo#1", voc:"🧑‍🚒 EK [Elite Knight]", level:870, primal:"", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Espada Larga", servidor:"Serenian [Eldrian] 🟢 🛡🚫", conta:"Marcelo#1", voc:"🧑‍🚒 EK [Elite Knight]", level:579, primal:"", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Sorcerer da Besta Fera", servidor:"Solarian 🟢 🛡", conta:"Marcelo#1", voc:"🧙‍♂️ MS [Master Sorcerer]", level:570, primal:"", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Sa Bour Energetico", servidor:"Serenian [Eldrian] 🟢 🛡🚫", conta:"Marcelo#1", voc:"👷RP [Royal Paladin]", level:550, primal:"", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Mago Cajadudo", servidor:"Tenebrium (blocked)", conta:"Marcelo#1", voc:"🧙‍♂️ MS [Master Sorcerer]", level:400, primal:"", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Diagonex", servidor:"Tenebrium (blocked)", conta:"Marcelo#1", voc:"🧝🏼 ED [Elder Druid]", level:400, primal:"", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Low Batata", servidor:"Malveria (blocked)", conta:"Marcelo#1", voc:"🧑‍🚒 EK [Elite Knight]", level:440, primal:"", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Apachh", servidor:"Malveria (blocked)", conta:"Marcelo#1", voc:"🧑‍🚒 EK [Elite Knight]", level:600, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Mago sem Criatividade", servidor:"Solarian 🟢 🛡", conta:"Marcelo#2", voc:"🧙‍♂️ MS [Master Sorcerer]", level:600, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Artista Sufacado", servidor:"Solarian 🟢 🛡", conta:"Marcelo#2", voc:"🧙‍♂️ MS [Master Sorcerer]", level:600, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Curo Ateaalma", servidor:"Solarian 🟢 🛡", conta:"Marcelo#2", voc:"🧝🏼 ED [Elder Druid]", level:601, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Mago Kicura", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"Marcelo#2", voc:"🧝🏼 ED [Elder Druid]", level:400, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Merlin da Silva", servidor:"Belaria 🟢", conta:"Marcelo#2", voc:"🧙‍♂️ MS [Master Sorcerer]", level:632, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Lostt druid", servidor:"Solarian 🟢 🛡", conta:"Marcelo#2", voc:"🧑‍🚒 EK [Elite Knight]", level:614, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Druida do Cetro Longo", servidor:"Solarian 🟢 🛡", conta:"Marcelo#2", voc:"🧝🏼 ED [Elder Druid]", level:515, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Rodanur", servidor:"Solarian 🟢 🛡", conta:"Marcelo#2", voc:"🧙‍♂️ MS [Master Sorcerer]", level:600, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Escravo da Flor", servidor:"Solarian 🟢 🛡", conta:"Marcelo#2", voc:"🧙‍♂️ MS [Master Sorcerer]", level:600, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Kashanjuice", servidor:"Belaria 🟢", conta:"Marcelo#2", voc:"🧝🏼 ED [Elder Druid]", level:548, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Encantador de Pedras", servidor:"Solarian 🟢 🛡", conta:"Marcelo#2", voc:"🧝🏼 ED [Elder Druid]", level:489, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Fazenda de Ava", servidor:"Solarian 🟢 🛡", conta:"Marcelo#2", voc:"🧝🏼 ED [Elder Druid]", level:600, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Entranamente Faixacolorida", servidor:"(New Server) 🟢 ⚔🚫", conta:"Marcelo#2", voc:"🧑‍🚒 EK [Elite Knight]", level:1, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Montisanti Hotyoga", servidor:"", conta:"", voc:"", level:null, primal:"", soulwar:null, sanguine:null, graveborn:null},
  {vendido:false, nome:"Old Tito", servidor:"Malveria 🟢 🚫", conta:"Rafa", voc:"🧑‍🚒 EK [Elite Knight]", level:525, primal:"5/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Lord Phillips", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"Rafa", voc:"🧙‍♂️ MS [Master Sorcerer]", level:857, primal:"11/12", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Ayuka Druid", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"Rafa", voc:"🧝🏼 ED [Elder Druid]", level:467, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Talonz", servidor:"Malveria 🟢 🚫", conta:"Rafa", voc:"👷RP [Royal Paladin]", level:599, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Rafa Grimoriano", servidor:"Grimoria II [Malveria] 🟢 🚫", conta:"Rafa", voc:"🧝🏼 ED [Elder Druid]", level:878, primal:"12/12", soulwar:true, sanguine:true, graveborn:false},
  {vendido:false, nome:"Dan Do Posto", servidor:"Eldrian 🟢 🛡🚫", conta:"Rafa", voc:"👷RP [Royal Paladin]", level:493, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Rafapguia", servidor:"Elysian 🟠 🛡", conta:"Rafa", voc:"🧑‍🚒 EK [Elite Knight]", level:980, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Roobertchay Faixacolorida", servidor:"Infernum 🟢 ⚔🚫", conta:"Rafa", voc:"🧝🏼 ED [Elder Druid]", level:2, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Rafa de Novo", servidor:"Grimoria II [Malveria] 🟢 🚫", conta:"Rafa", voc:"🧝🏼 ED [Elder Druid]", level:365, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Ambrozz", servidor:"Eldrian 🟢 🛡🚫", conta:"Rafa", voc:"👷RP [Royal Paladin]", level:616, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Baby Bluee", servidor:"Grimoria II [Malveria] 🟢 🚫", conta:"Rafa", voc:"👷RP [Royal Paladin]", level:764, primal:"1/12", soulwar:false, sanguine:false, graveborn:true},
  {vendido:false, nome:"Moscou tomou", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"Thiago", voc:"🧝🏼 ED [Elder Druid]", level:502, primal:"7/12", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Palahontas", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"Thiago", voc:"👷RP [Royal Paladin]", level:740, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Kingii", servidor:"Grimoria II [Malveria] 🟢 🚫", conta:"Thiago", voc:"👷RP [Royal Paladin]", level:775, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Dona Giovana", servidor:"Malveria (blocked)", conta:"Thiago", voc:"🧝🏼 ED [Elder Druid]", level:575, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Pelhen", servidor:"Malveria (blocked)", conta:"Thiago", voc:"👷RP [Royal Paladin]", level:843, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Mallzyn", servidor:"Malveria (blocked)", conta:"Thiago", voc:"👷RP [Royal Paladin]", level:501, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Naovinada", servidor:"Malveria (blocked)", conta:"Thiago", voc:"🧑‍🚒 EK [Elite Knight]", level:450, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Skan shadow", servidor:"Eldrian (blocked)", conta:"Thiago", voc:"🧝🏼 ED [Elder Druid]", level:450, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:true, nome:"Alif Grimoria", servidor:"Grimoria II [Malveria] 🟢 🚫", conta:"Alif", voc:"🧙‍♂️ MS [Master Sorcerer]", level:null, primal:"12/12", soulwar:true, sanguine:true, graveborn:false},
  {vendido:false, nome:"Perna Spectrum", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:null, primal:"7/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Maracujack", servidor:"Grimoria II [Malveria] 🟢 🚫", conta:"", voc:"🧙‍♂️ MS [Master Sorcerer]", level:null, primal:"", soulwar:false, sanguine:false, graveborn:false},
];

// Times / parties agrupados por servidor
const PARTIES = [
  {
    nome:"PT0 (Malveria)",
    membros:[
      {nome:"Knight Hot Yoga", voc:"🧑‍🚒 EK [Elite Knight]", level:870, primal:"12", primalReward:"Alicorn Headguard", soulwar:true, soulwarItem:"Soulbleeder", rotten:false},
      {nome:"Voyeur Hot Yoga", voc:"🧝🏼 ED [Elder Druid]", level:840, primal:"12", primalReward:"Arboreal Crown", soulwar:true, soulwarItem:"Soulshell", rotten:true, rottenItem:"Sanguine Battleaxe"},
      {nome:"Rafa Grimoriano", voc:"🧝🏼 ED [Elder Druid]", level:877, primal:"12", primalReward:"Arboreal Tome", soulwar:true, soulwarItem:"Soulsoles", rotten:false},
      {nome:"Alif Grimoria", voc:"🧙‍♂️ MS [Master Sorcerer]", level:null, primal:"12", primalReward:"Arboreal Ring", soulwar:true, soulwarItem:"Soulshredder", rotten:false},
      {nome:"Thiago Fofinho", voc:"👷RP [Royal Paladin]", level:null, primal:"12", primalReward:"Spiritthorn Armor 💶", soulwar:true, soulwarItem:"Soulshanks", rotten:true, rottenItem:"Sanguine Cudgel 💩"},
    ]
  },
  {
    nome:"PT0 (Bellum)",
    membros:[
      {nome:"Maricas", voc:"🧑‍🚒 EK [Elite Knight]", level:null, primal:"12", primalReward:"", soulwar:true, soulwarItem:"", rotten:false},
      {nome:"Maker Lopex", voc:"👷RP [Royal Paladin]", level:null, primal:"12", primalReward:"", soulwar:true, soulwarItem:"", rotten:false},
      {nome:"Mago Kicura", voc:"🧝🏼 ED [Elder Druid]", level:null, primal:"12", primalReward:"", soulwar:true, soulwarItem:"", rotten:false},
      {nome:"Ayuka Druid", voc:"🧝🏼 ED [Elder Druid]", level:null, primal:"12", primalReward:"", soulwar:true, soulwarItem:"", rotten:false},
      {nome:"Andicecream", voc:"🧕🏼 EM [Exalted Monk]", level:815, primal:"12", primalReward:"", soulwar:true, soulwarItem:"Soulpiercer", rotten:false},
    ]
  },
  {
    nome:"PT2 (Malveria)",
    membros:[
      {nome:"Dona Giovana", voc:"🧝🏼 ED [Elder Druid]", level:581, primal:"3", primalReward:"", soulwar:false, soulwarItem:"Soulbastion", soulwarTrue:true, rotten:false},
      {nome:"Holiex on Grimoria", voc:"🧝🏼 ED [Elder Druid]", level:375, primal:"3", primalReward:"", soulwar:false, soulwarItem:"Soulcutter", soulwarTrue:true, rotten:false},
      {nome:"Maracujack", voc:"🧙‍♂️ MS [Master Sorcerer]", level:402, primal:"3", primalReward:"", soulwar:false, soulwarItem:"Soulkamas 💷", soulwarTrue:true, rotten:false},
      {nome:"Montisanti Hotyoga", voc:"👷RP [Royal Paladin]", level:605, primal:"3", primalReward:"", soulwar:false, soulwarItem:"Soulbastion", soulwarTrue:true, rotten:false},
      {nome:"Old Tito", voc:"🧑‍🚒 EK [Elite Knight]", level:525, primal:"3", primalReward:"", soulwar:false, soulwarItem:"Soulcrusher", soulwarTrue:true, rotten:false},
    ]
  },
  {
    nome:"PT0 (Bellum) — grupo 2",
    membros:[
      {nome:"Leao cabecinha", voc:"🧑‍🚒 EK [Elite Knight]", level:null, primal:"12", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Creatina Frescca", voc:"🧝🏼 ED [Elder Druid]", level:690, primal:"12", primalReward:"Arcanomancer Regalia", soulwar:true, soulwarItem:"Pair of Soulstalkers", rotten:false},
      {nome:"Primo do Luis", voc:"👷RP [Royal Paladin]", level:null, primal:"12", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Ezrael", voc:"👷RP [Royal Paladin]", level:null, primal:"12", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Lopex", voc:"🧙‍♂️ MS [Master Sorcerer]", level:null, primal:"12", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
    ]
  },
  {
    nome:"PT1 (Bellum)",
    membros:[
      {nome:"Bloody Mind", voc:"🧑‍🚒 EK [Elite Knight]", level:null, primal:"12", primalReward:"Arcanomancer Sigil", soulwar:true, soulwarItem:"Soulbastion", rotten:false},
      {nome:"Redhaired Shanks", voc:"👷RP [Royal Paladin]", level:730, primal:"12", primalReward:"Arcanomancer Sigil", soulwar:true, soulwarItem:"Soulsoles", rotten:false},
      {nome:"Moscou tomou", voc:"🧝🏼 ED [Elder Druid]", level:null, primal:"12", primalReward:"Arcanomancer Sigil", soulwar:true, soulwarItem:"Pair of Soulstalkers", rotten:false},
      {nome:"Lord Phillips", voc:"🧙‍♂️ MS [Master Sorcerer]", level:null, primal:"12", primalReward:"Spiritthorn Armor 💶", soulwar:true, soulwarItem:"Soultainter", rotten:false},
      {nome:"Perna Spectrum", voc:"🧝🏼 ED [Elder Druid]", level:null, primal:"12", primalReward:"Arboreal Crown", soulwar:true, soulwarItem:"Soulbleeder", rotten:false},
    ]
  },
  {
    nome:"PT4 (Bellum)",
    membros:[]
  },
  {
    nome:"PT1 (Elderring)",
    membros:[
      {nome:"Espada Larga", voc:"🧑‍🚒 EK [Elite Knight]", level:null, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Sabor Ice", voc:"🧙‍♂️ MS [Master Sorcerer]", level:null, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Reqviem", voc:"🧝🏼 ED [Elder Druid]", level:574, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Thiago (nick)", voc:"", level:null, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Dan Do Posto", voc:"👷RP [Royal Paladin]", level:493, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
    ]
  },
  {
    nome:"PT0 (New Server)",
    membros:[
      {nome:"Faixacolorida Entranamente", voc:"🧑‍🚒 EK [Elite Knight]", level:0, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Roobertchay Faixacolorida", voc:"🧝🏼 ED [Elder Druid]", level:0, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Dolly Citros", voc:"🧝🏼 ED [Elder Druid]", level:0, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"", voc:"🧙‍♂️ MS [Master Sorcerer]", level:0, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"", voc:"👷RP [Royal Paladin]", level:0, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
    ]
  },
  {
    nome:"Sanguine?! (Bellum)",
    membros:[
      {nome:"Bloody Mind", voc:"🧑‍🚒 EK [Elite Knight]", level:null, primal:"1", primalReward:"", soulwar:true, soulwarItem:"", rotten:false},
      {nome:"Necroyster", voc:"🧝🏼 ED [Elder Druid]", level:null, primal:"1", primalReward:"", soulwar:true, soulwarItem:"", rotten:false},
      {nome:"Primo do Luis", voc:"👷RP [Royal Paladin]", level:null, primal:"1", primalReward:"", soulwar:true, soulwarItem:"", rotten:false},
      {nome:"Lord Phillips", voc:"🧙‍♂️ MS [Master Sorcerer]", level:857, primal:"1", primalReward:"", soulwar:true, soulwarItem:"", rotten:false},
      {nome:"", voc:"", level:null, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
    ]
  },
  {
    nome:"PT5 (Grimoria)",
    membros:[
      {nome:"Character Name", voc:"🧑‍🚒 EK [Elite Knight]", level:0, primal:"2", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Dieguito Maradona", voc:"🧝🏼 ED [Elder Druid]", level:0, primal:"2", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Character Name", voc:"🧝🏼 ED [Elder Druid]", level:0, primal:"2", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"", voc:"🧙‍♂️ MS [Master Sorcerer]", level:0, primal:"2", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"", voc:"👷RP [Royal Paladin]", level:0, primal:"2", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
    ]
  },
];

// Catálogo mestre de itens (nomes reais extraídos da planilha, com imagem correspondente em ITEM_IMAGES)
const ITEM_REFERENCE = [
  "Alicorn Headguard",
  "Alicorn Quiver",
  "Alicorn Ring",
  "Ancient Crypt Rune",
  "Arboreal Crown",
  "Arboreal Ring",
  "Arboreal Tome",
  "Arcanomancer Folio",
  "Arcanomancer Regalia",
  "Arcanomancer Sigil",
  "Auric Moon Sigil",
  "Bag You Covet",
  "Bag You Desire",
  "Cloud in a Bottle",
  "Coin",
  "Crypt Bile",
  "Crypt Breaker",
  "Crypt Jaw",
  "Crypt Slicer 💶",
  "Crypt Spine",
  "Crypt Splitter",
  "Crypt Strike",
  "Deathly Crypt Rune",
  "Enchanted Flamingo Amulet of Destruction",
  "Enchanted Flamingo Amulet of Nature",
  "Enchanted Flamingo Amulet of Precision",
  "Enchanted Flamingo Amulet of Valor",
  "Enchanted Swan Amulet of Balance",
  "Ethereal Coned Hat",
  "Ethereal Ring",
  "Fiery Crypt Rune",
  "Icy Crypt Rune",
  "Moonsilver Axe",
  "Moonsilver Battle Visor",
  "Moonsilver Bow",
  "Moonsilver Channeler",
  "Moonsilver Chopper",
  "Moonsilver Claymore",
  "Moonsilver Crossbow",
  "Moonsilver Crusher",
  "Moonsilver Epee",
  "Moonsilver Katar",
  "Moonsilver Mace",
  "Moonsilver Nimbus Hat",
  "Moonsilver Sceptre",
  "Moonsilver Spirit Mask",
  "Moonsilver Strike Helm",
  "Moonsilver Trail Hood",
  "Mystic Bag",
  "Necromantic Crypt Rune",
  "Pair of Soulstalkers",
  "Pair of Soulwalkers",
  "Primal Bag",
  "Rubini Coin",
  "Sanguine Battleaxe",
  "Sanguine Blade",
  "Sanguine Bludgeon",
  "Sanguine Boots",
  "Sanguine Bow 💴",
  "Sanguine Claw",
  "Sanguine Coil 💵",
  "Sanguine Crossbow",
  "Sanguine Cudgel 💩",
  "Sanguine Galoshes",
  "Sanguine Greaves",
  "Sanguine Hatchet",
  "Sanguine Legs",
  "Sanguine Razor",
  "Sanguine Rod",
  "Sanguine Trousers",
  "Soulbastion",
  "Soulbiter",
  "Soulbleeder 💸",
  "Soulcrusher",
  "Soulcutter",
  "Souleater",
  "Soulgarb",
  "Soulhexer",
  "Soulkamas 💷",
  "Soulmaimer",
  "Soulmantle",
  "Soulpiercer",
  "Soulshanks",
  "Soulshell",
  "Soulshredder",
  "Soulshroud",
  "Soulsoles",
  "Soulstrider",
  "Soultainter",
  "Spiritthorm Helmet",
  "Spiritthorn Armor 💶",
  "Spiritthorn Ring"
];

const SERVER_REFERENCE = [
  "Bellum 🟢 ⚔ 🆓🔁","Auroria 🟠","Belaria 🟢","Serenian (blocked)","Solarian 🟢 🛡","Elysian 🟠 🛡","Lunarian 🟠 🛡","Mystian 🟢 🛡",
  "Vesperia (blocked)","Drakaria (blocked)","Eldrian (blocked)","Malvéria (blocked)","Obsidian (blocked)",
];

const SHEET_USERS = ["Arthur","Marcelo ♿","Thiago Gutierrez","Alif","Rafa","Lopex","Thiago Fofinho"];
const ITEM_IMAGES = {
  "Primal Bag": "primal-bag.gif",
  "Alicorn Headguard": "alicorn-headguard.gif",
  "Alicorn Quiver": "alicorn-quiver.gif",
  "Alicorn Ring": "alicorn-ring.gif",
  "Arboreal Crown": "arboreal-crown.gif",
  "Arboreal Ring": "arboreal-ring.gif",
  "Arboreal Tome": "arboreal-tome.gif",
  "Arcanomancer Folio": "arcanomancer-folio.gif",
  "Arcanomancer Regalia": "arcanomancer-regalia.gif",
  "Arcanomancer Sigil": "arcanomancer-sigil.gif",
  "Ethereal Coned Hat": "ethereal-coned-hat.gif",
  "Ethereal Ring": "ethereal-ring.gif",
  "Spiritthorn Armor 💶": "spiritthorn-armor.gif",
  "Spiritthorm Helmet": "spiritthorm-helmet.gif",
  "Spiritthorn Ring": "spiritthorn-ring.gif",
  "Bag You Desire": "bag-you-desire.gif",
  "Pair of Soulstalkers": "pair-of-soulstalkers.gif",
  "Pair of Soulwalkers": "pair-of-soulwalkers.gif",
  "Soulbastion": "soulbastion.gif",
  "Soulbiter": "soulbiter.gif",
  "Soulbleeder 💸": "soulbleeder.gif",
  "Soulcrusher": "soulcrusher.gif",
  "Soulcutter": "soulcutter.gif",
  "Souleater": "souleater.gif",
  "Soulgarb": "soulgarb.gif",
  "Soulhexer": "soulhexer.gif",
  "Soulkamas 💷": "soulkamas.gif",
  "Soulmaimer": "soulmaimer.gif",
  "Soulmantle": "soulmantle.gif",
  "Soulpiercer": "soulpiercer.gif",
  "Soulshanks": "soulshanks.gif",
  "Soulshell": "soulshell.gif",
  "Soulshredder": "soulshredder.gif",
  "Soulshroud": "soulshroud.gif",
  "Soulsoles": "soulsoles.gif",
  "Soulstrider": "soulstrider.gif",
  "Soultainter": "soultainter.gif",
  "Bag You Covet": "bag-you-covet.gif",
  "Sanguine Battleaxe": "sanguine-battleaxe.gif",
  "Sanguine Blade": "sanguine-blade.gif",
  "Sanguine Bludgeon": "sanguine-bludgeon.gif",
  "Sanguine Boots": "sanguine-boots.gif",
  "Sanguine Bow 💴": "sanguine-bow.gif",
  "Sanguine Claw": "sanguine-claw.gif",
  "Sanguine Coil 💵": "sanguine-coil.gif",
  "Sanguine Crossbow": "sanguine-crossbow.gif",
  "Sanguine Cudgel 💩": "sanguine-cudgel.gif",
  "Sanguine Galoshes": "sanguine-galoshes.gif",
  "Sanguine Greaves": "sanguine-greaves.gif",
  "Sanguine Hatchet": "sanguine-hatchet.gif",
  "Sanguine Legs": "sanguine-legs.gif",
  "Sanguine Razor": "sanguine-razor.gif",
  "Sanguine Rod": "sanguine-rod.gif",
  "Sanguine Trousers": "sanguine-trousers.gif",
  "Fiery Crypt Rune": "fiery-crypt-rune.gif",
  "Icy Crypt Rune": "icy-crypt-rune.gif",
  "Deathly Crypt Rune": "deathly-crypt-rune.gif",
  "Ancient Crypt Rune": "ancient-crypt-rune.gif",
  "Necromantic Crypt Rune": "necromantic-crypt-rune.gif",
  "Crypt Spine": "crypt-spine.gif",
  "Crypt Splitter": "crypt-splitter.gif",
  "Crypt Breaker": "crypt-breaker.gif",
  "Crypt Strike": "crypt-strike.gif",
  "Crypt Bile": "crypt-bile.gif",
  "Crypt Jaw": "crypt-jaw.gif",
  "Crypt Slicer 💶": "crypt-slicer.gif",
  "Rubini Coin": "rubini-coin.gif",
  "Mystic Bag": "mystic-bag.gif",
  "Coin": "coin.gif",
  "Enchanted Flamingo Amulet of Destruction": "enchanted-flamingo-amulet-of-destruction.gif",
  "Enchanted Flamingo Amulet of Nature": "enchanted-flamingo-amulet-of-nature.gif",
  "Enchanted Flamingo Amulet of Precision": "enchanted-flamingo-amulet-of-precision.gif",
  "Enchanted Flamingo Amulet of Valor": "enchanted-flamingo-amulet-of-valor.gif",
  "Enchanted Swan Amulet of Balance": "enchanted-swan-amulet-of-balance.gif",
  "Cloud in a Bottle": "cloud-in-a-bottle.gif",
  "Auric Moon Sigil": "auric-moon-sigil.gif",
  "Moonsilver Battle Visor": "moonsilver-battle-visor.gif",
  "Moonsilver Nimbus Hat": "moonsilver-nimbus-hat.gif",
  "Moonsilver Spirit Mask": "moonsilver-spirit-mask.gif",
  "Moonsilver Strike Helm": "moonsilver-strike-helm.gif",
  "Moonsilver Trail Hood": "moonsilver-trail-hood.gif",
  "Moonsilver Axe": "moonsilver-axe.gif",
  "Moonsilver Bow": "moonsilver-bow.gif",
  "Moonsilver Channeler": "moonsilver-channeler.gif",
  "Moonsilver Chopper": "moonsilver-chopper.gif",
  "Moonsilver Claymore": "moonsilver-claymore.gif",
  "Moonsilver Crusher": "moonsilver-crusher.gif",
  "Moonsilver Crossbow": "moonsilver-crossbow.gif",
  "Moonsilver Epee": "moonsilver-epee.gif",
  "Moonsilver Katar": "moonsilver-katar.gif",
  "Moonsilver Mace": "moonsilver-mace.gif",
  "Moonsilver Sceptre": "moonsilver-sceptre.gif"
};
