// Dados extraídos da planilha de controle de loot da guild.
// Estrutura simples em arrays de objetos, um bloco por aba.

const DROPS = [
  {id:1, item:"Soulbleeder 💸", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Soulwar [chest]", resp:"PT", data:"04/07/2026", status:"Vendido(a)", valor:"7000rc", obs:"Saldo da PT"},
  {id:2, item:"Soulshredder", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Soulwar [chest]", resp:"PT", data:"04/07/2026", status:"Vendido(a)", valor:"150kk", obs:"Saldo da PT"},
  {id:3, item:"Soulsoles", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Soulwar [chest]", resp:"Alif", data:"04/07/2026", status:"Vendido(a)", valor:"14kk", obs:"Saldo da PT"},
  {id:4, item:"Soulshell", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Soulwar [chest]", resp:"PT", data:"04/07/2026", status:"Vendido(a)", valor:"125kk", obs:"Saldo da PT"},
  {id:5, item:"Soulshanks", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Soulwar [chest]", resp:"PT", data:"04/07/2026", status:"Vendido(a)", valor:"42kk", obs:"Saldo da PT"},
  {id:6, item:"Arboreal Crown", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Primal Ordeal [reward]", resp:"PT", data:"06/07/2026", status:"Usando", valor:"0", obs:"Arthur"},
  {id:7, item:"Spiritthorm Helmet", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Primal Ordeal [reward]", resp:"Rafa", data:"06/07/2026", status:"Vendido(a)", valor:"117kk", obs:"Era um Alicorn Headguard, foi trocado por um Spirritthorn Helmet. Vendido por 117kk"},
  {id:8, item:"Arboreal Tome", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Primal Ordeal [reward]", resp:"PT", data:"06/07/2026", status:"Usando", valor:"", obs:"Rafa"},
  {id:9, item:"Arboreal Ring", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Primal Ordeal [reward]", resp:"PT", data:"06/07/2026", status:"Usando", valor:"", obs:"Rafa"},
  {id:10, item:"Spiritthorn Armor 💶", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Primal Ordeal [reward]", resp:"PT", data:"06/07/2026", status:"Usando", valor:"0", obs:"Marcelo ♿"},
  {id:11, item:"Pair of Soulwalkers", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Soulwar [chest]", resp:"PT", data:"10/07/2026", status:"Vendido(a)", valor:"150kk", obs:"Saldo da PT"},
  {id:12, item:"Soulbleeder 💸", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Soulwar [chest]", resp:"PT", data:"10/07/2026", status:"Vendido(a)", valor:"7000rc", obs:"Saldo da PT"},
  {id:13, item:"Soulshell", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Soulwar [chest]", resp:"PT", data:"10/07/2026", status:"Usando", valor:"0", obs:"Thiago"},
  {id:14, item:"Soulbastion", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Soulwar [chest]", resp:"PT", data:"10/07/2026", status:"Usando", valor:"0", obs:"Marcelo ♿"},
  {id:15, item:"Pair of Soulwalkers", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Soulwar [chest]", resp:"PT", data:"10/07/2026", status:"Usando", valor:"0", obs:"Marcelo ♿"},
  {id:16, item:"Bag You Covet", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Ichgahal", resp:"Alif", data:"", status:"Aberto(a)", valor:"0", obs:""},
  {id:17, item:"Sanguine Bow 💴", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Bag You Covet", resp:"Arthur", data:"30/07/2026", status:"Vendido(a)", valor:"18.25k rc", obs:""},
  {id:18, item:"Bag You Covet", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Rotten Blood (1st)", resp:"Thiago Fofinho", data:"", status:"Aberto(a)", valor:"0", obs:""},
  {id:19, item:"Sanguine Cudgel 💩", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Bag You Covet", resp:"Alif", data:"05/08/2026", status:"Vendido(a)", valor:"17kk", obs:"Saldo da PT"},
  {id:20, item:"Bag You Covet", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Rotten Blood (1st)", resp:"Arthur", data:"", status:"Aberto(a)", valor:"0", obs:""},
  {id:21, item:"Sanguine Battleaxe", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Bag You Covet", resp:"Alif", data:"05/08/2026", status:"Vendido(a)", valor:"24kk", obs:"Saldo da PT"},
  {id:22, item:"Soulbastion", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", origem:"Soulwar [chest]", resp:"PT", data:"07/08/2026", status:"Vendido(a)", valor:"45kk", obs:"Saldo da PT"},
  {id:23, item:"Soulbleeder 💸", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", origem:"Soulwar [chest]", resp:"PT", data:"07/08/2026", status:"Vendido(a)", valor:"300kk", obs:"Saldo da PT"},
  {id:24, item:"Soultainter", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", origem:"Soulwar [chest]", resp:"PT", data:"07/08/2026", status:"A Venda", valor:"", obs:"Market por 74kk"},
  {id:25, item:"Soulsoles", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", origem:"Soulwar [chest]", resp:"PT", data:"07/08/2026", status:"Vendido(a)", valor:"18kk", obs:"Saldo da PT"},
  {id:26, item:"Pair of Soulstalkers", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", origem:"Soulwar [chest]", resp:"PT", data:"07/08/2026", status:"A Venda", valor:"", obs:"Market 148kk"},
  {id:27, item:"Ancient Crypt Rune", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Graveborn", resp:"PT", data:"10/08/2026", status:"Vendido(a)", valor:"27kk", obs:"Usado pra pagar obelisk"},
  {id:28, item:"Ancient Crypt Rune", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Graveborn", resp:"PT", data:"10/08/2026", status:"Vendido(a)", valor:"21k", obs:"comprado fiery cript"},
  {id:29, item:"Ancient Crypt Rune", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Graveborn", resp:"PT", data:"10/08/2026", status:"Vendido(a)", valor:"15k", obs:"comprado death crypt"},
  {id:30, item:"Icy Crypt Rune", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Graveborn", resp:"Marcelo ♿", data:"10/08/2026", status:"Pendente", valor:"", obs:""},
  {id:31, item:"Ancient Crypt Rune", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Graveborn", resp:"Thiago Fofinho", data:"10/08/2026", status:"Pendente", valor:"", obs:""},
  {id:32, item:"Fiery Crypt Rune", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Market", resp:"Thiago Fofinho", data:"10/08/2026", status:"Vendido(a)", valor:"8kk", obs:""},
  {id:33, item:"Deathly Crypt Rune", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Market", resp:"Thiago Fofinho", data:"10/08/2026", status:"Vendido(a)", valor:"20kk", obs:""},
  {id:34, item:"Spiritthorn Armor 💶", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Magma Bubble", resp:"Alif", data:"25/08/2026", status:"Vendido(a)", valor:"109kk", obs:"Saldo da PT"},
  {id:null, item:"Bag You Covet", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Rotten Blood (1st)", resp:"Thiago Fofinho", data:"09/01/2026", status:"Aberto(a)", valor:"", obs:""},
  {id:null, item:"Sanguine Hatchet", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Bag You Covet", resp:"Alif", data:"", status:"Pendente", valor:"", obs:""},
  {id:null, item:"Bag You Covet", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Rotten Blood (1st)", resp:"Alif", data:"", status:"Aberto(a)", valor:"", obs:""},
  {id:null, item:"Sanguine Crossbow", servidor:"Grimoria II [Malveria] 🟢 🚫", origem:"Bag You Covet", resp:"Alif", data:"", status:"Vendido(a)", valor:"100KK", obs:"Saldo PT"},
  {id:null, item:"Necromantic Crypt Rune", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", origem:"Graveborn", resp:"Arthur", data:"", status:"Trocado(a)", valor:"", obs:"Trocado por item final da quest"},
  {id:null, item:"Ancient Crypt Rune", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", origem:"Graveborn", resp:"", data:"", status:"Trocado(a)", valor:"", obs:"Trocado por item final da quest"},
  {id:null, item:"Deathly Crypt Rune", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", origem:"Graveborn", resp:"", data:"", status:"Trocado(a)", valor:"", obs:"Trocado por item final da quest"},
  {id:null, item:"Icy Crypt Rune", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", origem:"Graveborn", resp:"", data:"", status:"Trocado(a)", valor:"", obs:"Trocado por item final da quest"},
  {id:null, item:"Fiery Crypt Rune", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", origem:"Graveborn", resp:"Thiago Gutierrez", data:"", status:"Trocado(a)", valor:"", obs:"Trocado por item final da quest"},
  {id:null, item:"Crypt Splitter", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", origem:"Graveborn", resp:"Arthur", data:"09/02/2026", status:"Vendido(a)", valor:"345kk", obs:"Market — Saldo da PT"},
  {id:null, item:"Arcanomancer Sigil", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", origem:"Primal Ordeal [reward]", resp:"Alif", data:"02/09/2026", status:"A Venda", valor:"", obs:""},
  {id:null, item:"Arcanomancer Sigil", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", origem:"Primal Ordeal [reward]", resp:"Alif", data:"02/09/2026", status:"A Venda", valor:"", obs:""},
  {id:null, item:"Arcanomancer Sigil", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", origem:"Primal Ordeal [reward]", resp:"Alif", data:"02/09/2026", status:"A Venda", valor:"", obs:""},
  {id:null, item:"Spiritthorn Armor 💶", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", origem:"Primal Ordeal [reward]", resp:"Marcelo ♿", data:"02/09/2026", status:"Usando", valor:"", obs:"Vai ser comprado pelo Marcelo"},
  {id:null, item:"Arboreal Crown", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", origem:"Primal Ordeal [reward]", resp:"Alif", data:"", status:"A Venda", valor:"", obs:""},
  {id:null, item:"Soulcutter", servidor:"Malveria 🟢 🚫", origem:"Soulwar [chest]", resp:"Arthur", data:"09/05/2006", status:"", valor:"", obs:""},
  {id:null, item:"Soulkamas 💷", servidor:"Malveria 🟢 🚫", origem:"Soulwar [chest]", resp:"Marcelo ♿", data:"09/05/2006", status:"", valor:"", obs:""},
  {id:null, item:"Soulcrusher", servidor:"Malveria 🟢 🚫", origem:"Soulwar [chest]", resp:"Rafa", data:"09/05/2006", status:"", valor:"", obs:""},
  {id:null, item:"Soulbastion", servidor:"Malveria 🟢 🚫", origem:"Soulwar [chest]", resp:"Thiago Fofinho", data:"09/05/2006", status:"", valor:"", obs:""},
  {id:null, item:"Soulbastion", servidor:"Malveria 🟢 🚫", origem:"Soulwar [chest]", resp:"Alif", data:"09/05/2006", status:"", valor:"", obs:""},
];

const CHARACTERS = [
  {vendido:false, nome:"Necroyster", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"Arthur#1", voc:"🧝🏼 ED [Elder Druid]", level:1130, primal:"12/12", soulwar:true, sanguine:true, graveborn:false},
  {vendido:false, nome:"Voyeur Hot Yoga", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:845, primal:"12/12", soulwar:true, sanguine:true, graveborn:true},
  {vendido:false, nome:"Andicecream", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"Arthur#1", voc:"🧕🏼 EM [Exalted Monk]", level:830, primal:"12/12", soulwar:true, sanguine:true, graveborn:false},
  {vendido:false, nome:"Bvlgary", servidor:"Belaria 🟢", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:810, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Redhaired Shanks", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"", voc:"👷RP [Royal Paladin]", level:720, primal:"12/12", soulwar:true, sanguine:true, graveborn:false},
  {vendido:false, nome:"Creatina Frescca", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:690, primal:"12/12", soulwar:true, sanguine:true, graveborn:false},
  {vendido:false, nome:"Fupp", servidor:"Solarian 🟢 🛡", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:650, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Mambalexq", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"", voc:"👷RP [Royal Paladin]", level:560, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Best", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"", voc:"🧑‍🚒 EK [Elite Knight]", level:550, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Reqviem", servidor:"Serenian [Eldrian] 🟢 🛡🚫", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:540, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Gabi Trans Nao Operada", servidor:"Auroria 🟠", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:406, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Sir Peace", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"", voc:"🧙‍♂️ MS [Master Sorcerer]", level:400, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Dra Marcia", servidor:"Grimoria III [Drakaria] 🟢 🚫", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:240, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Holiex On Grimoria", servidor:"Grimoria II [Malveria] 🟢 🚫", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:374, primal:"4/12", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Mango Jvicy", servidor:"Belaria 🟢", conta:"", voc:"🧙‍♂️ MS [Master Sorcerer]", level:350, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Dono da Sauna", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"Gmail", voc:"🧝🏼 ED [Elder Druid]", level:298, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Dolly Citros", servidor:"Infernum 🟢 ⚔🚫", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:0, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Dieguito Maradona", servidor:"Grimoria II [Malveria] 🟢 🚫", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:650, primal:"2/12", soulwar:null, sanguine:null, graveborn:null},
  {vendido:false, nome:"Primo do Luis", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"ThiagoG#1", voc:"👷RP [Royal Paladin]", level:758, primal:"12/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Maricas", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"ThiagoG#1", voc:"🧑‍🚒 EK [Elite Knight]", level:607, primal:"5/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Sabor Ice", servidor:"", conta:"", voc:"", level:null, primal:"", soulwar:null, sanguine:null, graveborn:null},
  {vendido:false, nome:"Leao cabecinha", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"Marcelo#1", voc:"🧑‍🚒 EK [Elite Knight]", level:730, primal:"", soulwar:true, sanguine:true, graveborn:false},
  {vendido:false, nome:"Ek Escolta", servidor:"Grimoria II [Malveria] 🟢 🚫", conta:"Marcelo#1", voc:"🧑‍🚒 EK [Elite Knight]", level:915, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Bloody Mind", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"Marcelo#1", voc:"🧑‍🚒 EK [Elite Knight]", level:870, primal:"7/12", soulwar:true, sanguine:true, graveborn:false},
  {vendido:false, nome:"Two Handed Sword", servidor:"Serenian [Eldrian] 🟢 🛡🚫", conta:"Marcelo#1", voc:"🧑‍🚒 EK [Elite Knight]", level:1000, primal:"", soulwar:true, sanguine:true, graveborn:false},
  {vendido:false, nome:"Ekdofin", servidor:"Serenian [Eldrian] 🟢 🛡🚫", conta:"Marcelo#1", voc:"🧑‍🚒 EK [Elite Knight]", level:1000, primal:"", soulwar:true, sanguine:true, graveborn:true},
  {vendido:false, nome:"Mago Win", servidor:"Tenebrium 🟢 ⚔🚫", conta:"Marcelo#1", voc:"🧙‍♂️ MS [Master Sorcerer]", level:1000, primal:"", soulwar:true, sanguine:true, graveborn:false},
  {vendido:false, nome:"Knight Hot Yoga", servidor:"Grimoria II [Malveria] 🟢 🚫", conta:"Marcelo#1", voc:"🧑‍🚒 EK [Elite Knight]", level:870, primal:"", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Espada Larga", servidor:"Serenian [Eldrian] 🟢 🛡🚫", conta:"Marcelo#1", voc:"🧑‍🚒 EK [Elite Knight]", level:579, primal:"", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Sorcerer da Besta Fera", servidor:"Solarian 🟢 🛡", conta:"Marcelo#1", voc:"🧙‍♂️ MS [Master Sorcerer]", level:570, primal:"", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Sa Bour Energetico", servidor:"Serenian [Eldrian] 🟢 🛡🚫", conta:"Marcelo#1", voc:"👷RP [Royal Paladin]", level:550, primal:"", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Mago Cajadudo", servidor:"Tenebrium (blocked)", conta:"Marcelo#1", voc:"🧙‍♂️ MS [Master Sorcerer]", level:400, primal:"", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Diagonex", servidor:"Tenebrium (blocked)", conta:"Marcelo#1", voc:"🧝🏼 ED [Elder Druid]", level:400, primal:"", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Low Batata", servidor:"Malveria (blocked)", conta:"Marcelo#1", voc:"🧑‍🚒 EK [Elite Knight]", level:440, primal:"", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Apachh", servidor:"Malveria (blocked)", conta:"Marcelo#1", voc:"🧑‍🚒 EK [Elite Knight]", level:600, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Mago sem Criatividade", servidor:"Solarian 🟢 🛡", conta:"Marcelo#2", voc:"🧙‍♂️ MS [Master Sorcerer]", level:600, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Artista Sufacado", servidor:"Solarian 🟢 🛡", conta:"Marcelo#2", voc:"🧙‍♂️ MS [Master Sorcerer]", level:600, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Curo Ateaalma", servidor:"Solarian 🟢 🛡", conta:"Marcelo#2", voc:"🧝🏼 ED [Elder Druid]", level:601, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Mago Kicura", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"Marcelo#2", voc:"🧝🏼 ED [Elder Druid]", level:400, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Merlin da Silva", servidor:"Belaria 🟢", conta:"Marcelo#2", voc:"🧙‍♂️ MS [Master Sorcerer]", level:632, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Lostt druid", servidor:"Solarian 🟢 🛡", conta:"Marcelo#2", voc:"🧑‍🚒 EK [Elite Knight]", level:614, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Druida do Cetro Longo", servidor:"Solarian 🟢 🛡", conta:"Marcelo#2", voc:"🧝🏼 ED [Elder Druid]", level:515, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Rodanur", servidor:"Solarian 🟢 🛡", conta:"Marcelo#2", voc:"🧙‍♂️ MS [Master Sorcerer]", level:600, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Escravo da Flor", servidor:"Solarian 🟢 🛡", conta:"Marcelo#2", voc:"🧙‍♂️ MS [Master Sorcerer]", level:600, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Kashanjuice", servidor:"Belaria 🟢", conta:"Marcelo#2", voc:"🧝🏼 ED [Elder Druid]", level:548, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Encantador de Pedras", servidor:"Solarian 🟢 🛡", conta:"Marcelo#2", voc:"🧝🏼 ED [Elder Druid]", level:489, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Fazenda de Ava", servidor:"Solarian 🟢 🛡", conta:"Marcelo#2", voc:"🧝🏼 ED [Elder Druid]", level:600, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Entranamente Faixacolorida", servidor:"(New Server) 🟢 ⚔🚫", conta:"Marcelo#2", voc:"🧑‍🚒 EK [Elite Knight]", level:1, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Montisanti Hotyoga", servidor:"", conta:"", voc:"", level:null, primal:"", soulwar:null, sanguine:null, graveborn:null},
  {vendido:false, nome:"Old Tito", servidor:"Malveria 🟢 🚫", conta:"Rafa", voc:"🧑‍🚒 EK [Elite Knight]", level:525, primal:"5/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Lord Phillips", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"Rafa", voc:"🧙‍♂️ MS [Master Sorcerer]", level:857, primal:"11/12", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Ayuka Druid", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"Rafa", voc:"🧝🏼 ED [Elder Druid]", level:467, primal:"", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Talonz", servidor:"Malveria 🟢 🚫", conta:"Rafa", voc:"👷RP [Royal Paladin]", level:599, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Rafa Grimoriano", servidor:"Grimoria II [Malveria] 🟢 🚫", conta:"Rafa", voc:"🧝🏼 ED [Elder Druid]", level:878, primal:"12/12", soulwar:true, sanguine:true, graveborn:false},
  {vendido:false, nome:"Dan Do Posto", servidor:"Eldrian 🟢 🛡🚫", conta:"Rafa", voc:"👷RP [Royal Paladin]", level:493, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Rafapguia", servidor:"Elysian 🟠 🛡", conta:"Rafa", voc:"🧑‍🚒 EK [Elite Knight]", level:980, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Roobertchay Faixacolorida", servidor:"Infernum 🟢 ⚔🚫", conta:"Rafa", voc:"🧝🏼 ED [Elder Druid]", level:2, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Rafa de Novo", servidor:"Grimoria II [Malveria] 🟢 🚫", conta:"Rafa", voc:"🧝🏼 ED [Elder Druid]", level:365, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Ambrozz", servidor:"Eldrian 🟢 🛡🚫", conta:"Rafa", voc:"👷RP [Royal Paladin]", level:616, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Baby Bluee", servidor:"Grimoria II [Malveria] 🟢 🚫", conta:"Rafa", voc:"👷RP [Royal Paladin]", level:764, primal:"1/12", soulwar:false, sanguine:false, graveborn:true},
  {vendido:false, nome:"Moscou tomou", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"Thiago", voc:"🧝🏼 ED [Elder Druid]", level:502, primal:"7/12", soulwar:false, sanguine:true, graveborn:false},
  {vendido:false, nome:"Palahontas", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"Thiago", voc:"👷RP [Royal Paladin]", level:740, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Kingii", servidor:"Grimoria II [Malveria] 🟢 🚫", conta:"Thiago", voc:"👷RP [Royal Paladin]", level:775, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Dona Giovana", servidor:"Malveria (blocked)", conta:"Thiago", voc:"🧝🏼 ED [Elder Druid]", level:575, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Pelhen", servidor:"Malveria (blocked)", conta:"Thiago", voc:"👷RP [Royal Paladin]", level:843, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Mallzyn", servidor:"Malveria (blocked)", conta:"Thiago", voc:"👷RP [Royal Paladin]", level:501, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Naovinada", servidor:"Malveria (blocked)", conta:"Thiago", voc:"🧑‍🚒 EK [Elite Knight]", level:450, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Skan shadow", servidor:"Eldrian (blocked)", conta:"Thiago", voc:"🧝🏼 ED [Elder Druid]", level:450, primal:"1/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:true, nome:"Alif Grimoria", servidor:"Grimoria II [Malveria] 🟢 🚫", conta:"Alif", voc:"🧙‍♂️ MS [Master Sorcerer]", level:null, primal:"12/12", soulwar:true, sanguine:true, graveborn:false},
  {vendido:false, nome:"Perna Spectrum", servidor:"Spectrum [Bellum] 🟢 ⚔ 🆓🔁", conta:"", voc:"🧝🏼 ED [Elder Druid]", level:null, primal:"7/12", soulwar:false, sanguine:false, graveborn:false},
  {vendido:false, nome:"Maracujack", servidor:"Grimoria II [Malveria] 🟢 🚫", conta:"", voc:"🧙‍♂️ MS [Master Sorcerer]", level:null, primal:"", soulwar:false, sanguine:false, graveborn:false},
];

// Times / parties agrupados por servidor
const PARTIES = [
  {
    nome:"PT0 (Malveria)",
    membros:[
      {nome:"Knight Hot Yoga", voc:"🧑‍🚒 EK [Elite Knight]", level:870, primal:"12", primalReward:"Alicorn Headguard", soulwar:true, soulwarItem:"Soulbleeder", rotten:false},
      {nome:"Voyeur Hot Yoga", voc:"🧝🏼 ED [Elder Druid]", level:840, primal:"12", primalReward:"Arboreal Crown", soulwar:true, soulwarItem:"Soulshell", rotten:true, rottenItem:"Sanguine Battleaxe"},
      {nome:"Rafa Grimoriano", voc:"🧝🏼 ED [Elder Druid]", level:877, primal:"12", primalReward:"Arboreal Tome", soulwar:true, soulwarItem:"Soulsoles", rotten:false},
      {nome:"Alif Grimoria", voc:"🧙‍♂️ MS [Master Sorcerer]", level:null, primal:"12", primalReward:"Arboreal Ring", soulwar:true, soulwarItem:"Soulshredder", rotten:false},
      {nome:"Thiago Fofinho", voc:"👷RP [Royal Paladin]", level:null, primal:"12", primalReward:"Spiritthorn Armor 💶", soulwar:true, soulwarItem:"Soulshanks", rotten:true, rottenItem:"Sanguine Cudgel 💩"},
    ]
  },
  {
    nome:"PT0 (Bellum)",
    membros:[
      {nome:"Maricas", voc:"🧑‍🚒 EK [Elite Knight]", level:null, primal:"12", primalReward:"", soulwar:true, soulwarItem:"", rotten:false},
      {nome:"Maker Lopex", voc:"👷RP [Royal Paladin]", level:null, primal:"12", primalReward:"", soulwar:true, soulwarItem:"", rotten:false},
      {nome:"Mago Kicura", voc:"🧝🏼 ED [Elder Druid]", level:null, primal:"12", primalReward:"", soulwar:true, soulwarItem:"", rotten:false},
      {nome:"Ayuka Druid", voc:"🧝🏼 ED [Elder Druid]", level:null, primal:"12", primalReward:"", soulwar:true, soulwarItem:"", rotten:false},
      {nome:"Andicecream", voc:"🧕🏼 EM [Exalted Monk]", level:815, primal:"12", primalReward:"", soulwar:true, soulwarItem:"Soulpiercer", rotten:false},
    ]
  },
  {
    nome:"PT2 (Malveria)",
    membros:[
      {nome:"Dona Giovana", voc:"🧝🏼 ED [Elder Druid]", level:581, primal:"3", primalReward:"", soulwar:false, soulwarItem:"Soulbastion", soulwarTrue:true, rotten:false},
      {nome:"Holiex on Grimoria", voc:"🧝🏼 ED [Elder Druid]", level:375, primal:"3", primalReward:"", soulwar:false, soulwarItem:"Soulcutter", soulwarTrue:true, rotten:false},
      {nome:"Maracujack", voc:"🧙‍♂️ MS [Master Sorcerer]", level:402, primal:"3", primalReward:"", soulwar:false, soulwarItem:"Soulkamas 💷", soulwarTrue:true, rotten:false},
      {nome:"Montisanti Hotyoga", voc:"👷RP [Royal Paladin]", level:605, primal:"3", primalReward:"", soulwar:false, soulwarItem:"Soulbastion", soulwarTrue:true, rotten:false},
      {nome:"Old Tito", voc:"🧑‍🚒 EK [Elite Knight]", level:525, primal:"3", primalReward:"", soulwar:false, soulwarItem:"Soulcrusher", soulwarTrue:true, rotten:false},
    ]
  },
  {
    nome:"PT0 (Bellum) — grupo 2",
    membros:[
      {nome:"Leao cabecinha", voc:"🧑‍🚒 EK [Elite Knight]", level:null, primal:"12", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Creatina Frescca", voc:"🧝🏼 ED [Elder Druid]", level:690, primal:"12", primalReward:"Arcanomancer Regalia", soulwar:true, soulwarItem:"Pair of Soulstalkers", rotten:false},
      {nome:"Primo do Luis", voc:"👷RP [Royal Paladin]", level:null, primal:"12", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Ezrael", voc:"👷RP [Royal Paladin]", level:null, primal:"12", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Lopex", voc:"🧙‍♂️ MS [Master Sorcerer]", level:null, primal:"12", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
    ]
  },
  {
    nome:"PT1 (Bellum)",
    membros:[
      {nome:"Bloody Mind", voc:"🧑‍🚒 EK [Elite Knight]", level:null, primal:"12", primalReward:"Arcanomancer Sigil", soulwar:true, soulwarItem:"Soulbastion", rotten:false},
      {nome:"Redhaired Shanks", voc:"👷RP [Royal Paladin]", level:730, primal:"12", primalReward:"Arcanomancer Sigil", soulwar:true, soulwarItem:"Soulsoles", rotten:false},
      {nome:"Moscou tomou", voc:"🧝🏼 ED [Elder Druid]", level:null, primal:"12", primalReward:"Arcanomancer Sigil", soulwar:true, soulwarItem:"Pair of Soulstalkers", rotten:false},
      {nome:"Lord Phillips", voc:"🧙‍♂️ MS [Master Sorcerer]", level:null, primal:"12", primalReward:"Spiritthorn Armor 💶", soulwar:true, soulwarItem:"Soultainter", rotten:false},
      {nome:"Perna Spectrum", voc:"🧝🏼 ED [Elder Druid]", level:null, primal:"12", primalReward:"Arboreal Crown", soulwar:true, soulwarItem:"Soulbleeder", rotten:false},
    ]
  },
  {
    nome:"PT4 (Bellum)",
    membros:[]
  },
  {
    nome:"PT1 (Elderring)",
    membros:[
      {nome:"Espada Larga", voc:"🧑‍🚒 EK [Elite Knight]", level:null, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Sabor Ice", voc:"🧙‍♂️ MS [Master Sorcerer]", level:null, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Reqviem", voc:"🧝🏼 ED [Elder Druid]", level:574, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Thiago (nick)", voc:"", level:null, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Dan Do Posto", voc:"👷RP [Royal Paladin]", level:493, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
    ]
  },
  {
    nome:"PT0 (New Server)",
    membros:[
      {nome:"Faixacolorida Entranamente", voc:"🧑‍🚒 EK [Elite Knight]", level:0, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Roobertchay Faixacolorida", voc:"🧝🏼 ED [Elder Druid]", level:0, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Dolly Citros", voc:"🧝🏼 ED [Elder Druid]", level:0, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"", voc:"🧙‍♂️ MS [Master Sorcerer]", level:0, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"", voc:"👷RP [Royal Paladin]", level:0, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
    ]
  },
  {
    nome:"Sanguine?! (Bellum)",
    membros:[
      {nome:"Bloody Mind", voc:"🧑‍🚒 EK [Elite Knight]", level:null, primal:"1", primalReward:"", soulwar:true, soulwarItem:"", rotten:false},
      {nome:"Necroyster", voc:"🧝🏼 ED [Elder Druid]", level:null, primal:"1", primalReward:"", soulwar:true, soulwarItem:"", rotten:false},
      {nome:"Primo do Luis", voc:"👷RP [Royal Paladin]", level:null, primal:"1", primalReward:"", soulwar:true, soulwarItem:"", rotten:false},
      {nome:"Lord Phillips", voc:"🧙‍♂️ MS [Master Sorcerer]", level:857, primal:"1", primalReward:"", soulwar:true, soulwarItem:"", rotten:false},
      {nome:"", voc:"", level:null, primal:"1", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
    ]
  },
  {
    nome:"PT5 (Grimoria)",
    membros:[
      {nome:"Character Name", voc:"🧑‍🚒 EK [Elite Knight]", level:0, primal:"2", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Dieguito Maradona", voc:"🧝🏼 ED [Elder Druid]", level:0, primal:"2", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"Character Name", voc:"🧝🏼 ED [Elder Druid]", level:0, primal:"2", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"", voc:"🧙‍♂️ MS [Master Sorcerer]", level:0, primal:"2", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
      {nome:"", voc:"👷RP [Royal Paladin]", level:0, primal:"2", primalReward:"", soulwar:false, soulwarItem:"", rotten:false},
    ]
  },
];

// Cotações de conversão (compra/venda) por servidor
const RATES_SERVERS = ["Bellum","Auroria","Belaria","Serenian (blocked)","Solarian","Elysian","Lunarian","Mystian"];
const RATES = [
  {moeda:"Rubini Coin", valores:{
    "Bellum":{venda:89949, compra:87357}, "Auroria":{venda:90285, compra:88721}, "Belaria":{venda:90700, compra:89330},
    "Serenian (blocked)":{venda:90800, compra:86130}, "Solarian":{venda:89987, compra:89003}, "Elysian":{venda:89700, compra:87230},
    "Lunarian":{venda:89699, compra:86303}, "Mystian":{venda:91036, compra:90005}
  }},
  {moeda:"Bleeder", valores:{
    "Bellum":{venda:350000000, compra:265000000}, "Auroria":{venda:339977888, compra:290000000}, "Belaria":{venda:350000000, compra:260000000},
    "Serenian (blocked)":{venda:445000000, compra:400000000}, "Solarian":{venda:448000000, compra:275397000}, "Elysian":{venda:304999999, compra:271337337},
    "Lunarian":{venda:314903903, compra:285000000}, "Mystian":{venda:349826826, compra:290050050}
  }},
  {moeda:"Tainter", valores:{
    "Bellum":{venda:104849844, compra:65100000}, "Auroria":{venda:70000000, compra:51167167}, "Belaria":{venda:68900000, compra:50000121},
    "Serenian (blocked)":{venda:139999999, compra:70025010}, "Solarian":{venda:81000000, compra:70099999}, "Elysian":{venda:128999000, compra:60600000},
    "Lunarian":{venda:69900000, compra:60006006}, "Mystian":{venda:64927927, compra:56155175}
  }},
  {moeda:"Soulstalker", valores:{
    "Bellum":{venda:157999997, compra:95500000}, "Auroria":{venda:121401401, compra:101000001}, "Belaria":{venda:126000000, compra:100025100},
    "Serenian (blocked)":{venda:179999999, compra:125100000}, "Solarian":{venda:114779999, compra:60600000}, "Elysian":{venda:125976000, compra:111000001},
    "Lunarian":{venda:109946946, compra:93025010}, "Mystian":{venda:125000000, compra:100094095}
  }},
];

// Rankings / recordes
const RANKINGS = [
  {servidor:"Grimoria II [Malveria] 🟢 🚫", topLevel:"Alif Grimoria", mvDrop:"Alif Grimoria — Sanguine Bow 💴", lessDeaths:"Voyeur Hot Yoga", topAvgDrop:"Holiex On Grimoria", goldenDrop:""},
  {servidor:"Infernum 🟢 ⚔🚫", topLevel:"", mvDrop:"", lessDeaths:"", topAvgDrop:"", goldenDrop:""},
];

// Catálogo mestre de itens (nomes reais extraídos da planilha, com imagem correspondente em ITEM_IMAGES)
const ITEM_REFERENCE = [
  "Alicorn Headguard",
  "Alicorn Quiver",
  "Alicorn Ring",
  "Ancient Crypt Rune",
  "Arboreal Crown",
  "Arboreal Ring",
  "Arboreal Tome",
  "Arcanomancer Folio",
  "Arcanomancer Regalia",
  "Arcanomancer Sigil",
  "Auric Moon Sigil",
  "Bag You Covet",
  "Bag You Desire",
  "Cloud in a Bottle",
  "Coin",
  "Crypt Bile",
  "Crypt Breaker",
  "Crypt Jaw",
  "Crypt Slicer 💶",
  "Crypt Spine",
  "Crypt Splitter",
  "Crypt Strike",
  "Deathly Crypt Rune",
  "Enchanted Flamingo Amulet of Destruction",
  "Enchanted Flamingo Amulet of Nature",
  "Enchanted Flamingo Amulet of Precision",
  "Enchanted Flamingo Amulet of Valor",
  "Enchanted Swan Amulet of Balance",
  "Ethereal Coned Hat",
  "Ethereal Ring",
  "Fiery Crypt Rune",
  "Icy Crypt Rune",
  "Moonsilver Axe",
  "Moonsilver Battle Visor",
  "Moonsilver Bow",
  "Moonsilver Channeler",
  "Moonsilver Chopper",
  "Moonsilver Claymore",
  "Moonsilver Crossbow",
  "Moonsilver Crusher",
  "Moonsilver Epee",
  "Moonsilver Katar",
  "Moonsilver Mace",
  "Moonsilver Nimbus Hat",
  "Moonsilver Sceptre",
  "Moonsilver Spirit Mask",
  "Moonsilver Strike Helm",
  "Moonsilver Trail Hood",
  "Mystic Bag",
  "Necromantic Crypt Rune",
  "Pair of Soulstalkers",
  "Pair of Soulwalkers",
  "Primal Bag",
  "Rubini Coin",
  "Sanguine Battleaxe",
  "Sanguine Blade",
  "Sanguine Bludgeon",
  "Sanguine Boots",
  "Sanguine Bow 💴",
  "Sanguine Claw",
  "Sanguine Coil 💵",
  "Sanguine Crossbow",
  "Sanguine Cudgel 💩",
  "Sanguine Galoshes",
  "Sanguine Greaves",
  "Sanguine Hatchet",
  "Sanguine Legs",
  "Sanguine Razor",
  "Sanguine Rod",
  "Sanguine Trousers",
  "Soulbastion",
  "Soulbiter",
  "Soulbleeder 💸",
  "Soulcrusher",
  "Soulcutter",
  "Souleater",
  "Soulgarb",
  "Soulhexer",
  "Soulkamas 💷",
  "Soulmaimer",
  "Soulmantle",
  "Soulpiercer",
  "Soulshanks",
  "Soulshell",
  "Soulshredder",
  "Soulshroud",
  "Soulsoles",
  "Soulstrider",
  "Soultainter",
  "Spiritthorm Helmet",
  "Spiritthorn Armor 💶",
  "Spiritthorn Ring"
];

const SERVER_REFERENCE = [
  "Bellum 🟢 ⚔ 🆓🔁","Auroria 🟠","Belaria 🟢","Serenian (blocked)","Solarian 🟢 🛡","Elysian 🟠 🛡","Lunarian 🟠 🛡","Mystian 🟢 🛡",
  "Vesperia (blocked)","Drakaria (blocked)","Eldrian (blocked)","Malvéria (blocked)","Obsidian (blocked)",
];

const SHEET_USERS = ["Arthur","Marcelo ♿","Thiago Gutierrez","Alif","Rafa","Lopex","Thiago Fofinho"];
const ITEM_IMAGES = {
  "Primal Bag": "primal-bag.gif",
  "Alicorn Headguard": "alicorn-headguard.gif",
  "Alicorn Quiver": "alicorn-quiver.gif",
  "Alicorn Ring": "alicorn-ring.gif",
  "Arboreal Crown": "arboreal-crown.gif",
  "Arboreal Ring": "arboreal-ring.gif",
  "Arboreal Tome": "arboreal-tome.gif",
  "Arcanomancer Folio": "arcanomancer-folio.gif",
  "Arcanomancer Regalia": "arcanomancer-regalia.gif",
  "Arcanomancer Sigil": "arcanomancer-sigil.gif",
  "Ethereal Coned Hat": "ethereal-coned-hat.gif",
  "Ethereal Ring": "ethereal-ring.gif",
  "Spiritthorn Armor 💶": "spiritthorn-armor.gif",
  "Spiritthorm Helmet": "spiritthorm-helmet.gif",
  "Spiritthorn Ring": "spiritthorn-ring.gif",
  "Bag You Desire": "bag-you-desire.gif",
  "Pair of Soulstalkers": "pair-of-soulstalkers.gif",
  "Pair of Soulwalkers": "pair-of-soulwalkers.gif",
  "Soulbastion": "soulbastion.gif",
  "Soulbiter": "soulbiter.gif",
  "Soulbleeder 💸": "soulbleeder.gif",
  "Soulcrusher": "soulcrusher.gif",
  "Soulcutter": "soulcutter.gif",
  "Souleater": "souleater.gif",
  "Soulgarb": "soulgarb.gif",
  "Soulhexer": "soulhexer.gif",
  "Soulkamas 💷": "soulkamas.gif",
  "Soulmaimer": "soulmaimer.gif",
  "Soulmantle": "soulmantle.gif",
  "Soulpiercer": "soulpiercer.gif",
  "Soulshanks": "soulshanks.gif",
  "Soulshell": "soulshell.gif",
  "Soulshredder": "soulshredder.gif",
  "Soulshroud": "soulshroud.gif",
  "Soulsoles": "soulsoles.gif",
  "Soulstrider": "soulstrider.gif",
  "Soultainter": "soultainter.gif",
  "Bag You Covet": "bag-you-covet.gif",
  "Sanguine Battleaxe": "sanguine-battleaxe.gif",
  "Sanguine Blade": "sanguine-blade.gif",
  "Sanguine Bludgeon": "sanguine-bludgeon.gif",
  "Sanguine Boots": "sanguine-boots.gif",
  "Sanguine Bow 💴": "sanguine-bow.gif",
  "Sanguine Claw": "sanguine-claw.gif",
  "Sanguine Coil 💵": "sanguine-coil.gif",
  "Sanguine Crossbow": "sanguine-crossbow.gif",
  "Sanguine Cudgel 💩": "sanguine-cudgel.gif",
  "Sanguine Galoshes": "sanguine-galoshes.gif",
  "Sanguine Greaves": "sanguine-greaves.gif",
  "Sanguine Hatchet": "sanguine-hatchet.gif",
  "Sanguine Legs": "sanguine-legs.gif",
  "Sanguine Razor": "sanguine-razor.gif",
  "Sanguine Rod": "sanguine-rod.gif",
  "Sanguine Trousers": "sanguine-trousers.gif",
  "Fiery Crypt Rune": "fiery-crypt-rune.gif",
  "Icy Crypt Rune": "icy-crypt-rune.gif",
  "Deathly Crypt Rune": "deathly-crypt-rune.gif",
  "Ancient Crypt Rune": "ancient-crypt-rune.gif",
  "Necromantic Crypt Rune": "necromantic-crypt-rune.gif",
  "Crypt Spine": "crypt-spine.gif",
  "Crypt Splitter": "crypt-splitter.gif",
  "Crypt Breaker": "crypt-breaker.gif",
  "Crypt Strike": "crypt-strike.gif",
  "Crypt Bile": "crypt-bile.gif",
  "Crypt Jaw": "crypt-jaw.gif",
  "Crypt Slicer 💶": "crypt-slicer.gif",
  "Rubini Coin": "rubini-coin.gif",
  "Mystic Bag": "mystic-bag.gif",
  "Coin": "coin.gif",
  "Enchanted Flamingo Amulet of Destruction": "enchanted-flamingo-amulet-of-destruction.gif",
  "Enchanted Flamingo Amulet of Nature": "enchanted-flamingo-amulet-of-nature.gif",
  "Enchanted Flamingo Amulet of Precision": "enchanted-flamingo-amulet-of-precision.gif",
  "Enchanted Flamingo Amulet of Valor": "enchanted-flamingo-amulet-of-valor.gif",
  "Enchanted Swan Amulet of Balance": "enchanted-swan-amulet-of-balance.gif",
  "Cloud in a Bottle": "cloud-in-a-bottle.gif",
  "Auric Moon Sigil": "auric-moon-sigil.gif",
  "Moonsilver Battle Visor": "moonsilver-battle-visor.gif",
  "Moonsilver Nimbus Hat": "moonsilver-nimbus-hat.gif",
  "Moonsilver Spirit Mask": "moonsilver-spirit-mask.gif",
  "Moonsilver Strike Helm": "moonsilver-strike-helm.gif",
  "Moonsilver Trail Hood": "moonsilver-trail-hood.gif",
  "Moonsilver Axe": "moonsilver-axe.gif",
  "Moonsilver Bow": "moonsilver-bow.gif",
  "Moonsilver Channeler": "moonsilver-channeler.gif",
  "Moonsilver Chopper": "moonsilver-chopper.gif",
  "Moonsilver Claymore": "moonsilver-claymore.gif",
  "Moonsilver Crusher": "moonsilver-crusher.gif",
  "Moonsilver Crossbow": "moonsilver-crossbow.gif",
  "Moonsilver Epee": "moonsilver-epee.gif",
  "Moonsilver Katar": "moonsilver-katar.gif",
  "Moonsilver Mace": "moonsilver-mace.gif",
  "Moonsilver Sceptre": "moonsilver-sceptre.gif"
};
